# Generated by Django 4.1.7 on 2023-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_bandusers_venue_event_attendees_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
