# Generated by Django 4.1.7 on 2023-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(default='Jack Black', max_length=60),
        ),
    ]
