# Generated by Django 4.1.7 on 2023-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
